addSbtPlugin("org.lyranthe.sbt" % "partial-unification" % "1.1.0")
//addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.3")
addSbtPlugin("io.spray" % "sbt-revolver" % "0.9.1")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.1.0-M1")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.3.4")
